export const countries = [
  { name: 'United States', code: 'US' },
  { name: 'Canada', code: 'CA' },
  { name: 'United Kingdom', code: 'GB' },
  { name: 'India', code: 'IN' },
];

export const states: { [countryCode: string]: { name: string; code: string }[] } = {
  US: [
    { name: 'California', code: 'CA' },
    { name: 'New York', code: 'NY' },
    { name: 'Texas', code: 'TX' },
  ],
  CA: [
    { name: 'Ontario', code: 'ON' },
    { name: 'Quebec', code: 'QC' },
    { name: 'British Columbia', code: 'BC' },
  ],
  GB: [
    { name: 'England', code: 'ENG' },
    { name: 'Scotland', code: 'SCT' },
    { name: 'Wales', code: 'WLS' },
  ],
  IN: [
    { name: 'Andhra Pradesh', code: 'AP' },
    { name: 'Arunachal Pradesh', code: 'AR' },
    { name: 'Assam', code: 'AS' },
    { name: 'Bihar', code: 'BR' },
    { name: 'Chhattisgarh', code: 'CG' },
    { name: 'Goa', code: 'GA' },
    { name: 'Gujarat', code: 'GJ' },
    { name: 'Haryana', code: 'HR' },
    { name: 'Himachal Pradesh', code: 'HP' },
    { name: 'Jharkhand', code: 'JH' },
    { name: 'Karnataka', code: 'KA' },
    { name: 'Kerala', code: 'KL' },
    { name: 'Madhya Pradesh', code: 'MP' },
    { name: 'Maharashtra', code: 'MH' },
    { name: 'Manipur', code: 'MN' },
    { name: 'Meghalaya', code: 'ML' },
    { name: 'Mizoram', code: 'MZ' },
    { name: 'Nagaland', code: 'NL' },
    { name: 'Odisha', code: 'OR' },
    { name: 'Punjab', code: 'PB' },
    { name: 'Rajasthan', code: 'RJ' },
    { name: 'Sikkim', code: 'SK' },
    { name: 'Tamil Nadu', code: 'TN' },
    { name: 'Telangana', code: 'TG' },
    { name: 'Tripura', code: 'TR' },
    { name: 'Uttar Pradesh', code: 'UP' },
    { name: 'Uttarakhand', code: 'UT' },
    { name: 'West Bengal', code: 'WB' },
    { name: 'Andaman and Nicobar Islands', code: 'AN' },
    { name: 'Chandigarh', code: 'CH' },
    { name: 'Dadra and Nagar Haveli and Daman and Diu', code: 'DH' },
    { name: 'Delhi', code: 'DL' },
    { name: 'Jammu and Kashmir', code: 'JK' },
    { name: 'Ladakh', code: 'LA' },
    { name: 'Lakshadweep', code: 'LD' },
    { name: 'Puducherry', code: 'PY' },
  ],
};

export const cities: { [stateCode: string]: { name: string }[] } = {
  CA: [
    { name: 'San Francisco' },
    { name: 'Los Angeles' },
    { name: 'San Diego' },
  ],
  NY: [{ name: 'New York City' }, { name: 'Buffalo' }, { name: 'Rochester' }],
  TX: [{ name: 'Houston' }, { name: 'Dallas' }, { name: 'Austin' }],
  ON: [{ name: 'Toronto' }, { name: 'Ottawa' }, { name: 'Mississauga' }],
  QC: [{ name: 'Montreal' }, { name: 'Quebec City' }, { name: 'Gatineau' }],
  BC: [{ name: 'Vancouver' }, { name: 'Victoria' }, { name: 'Surrey' }],
  ENG: [{ name: 'London' }, { name: 'Manchester' }, { name: 'Birmingham' }],
  SCT: [{ name: 'Glasgow' }, { name: 'Edinburgh' }, { name: 'Aberdeen' }],
  WLS: [{ name: 'Cardiff' }, { name: 'Swansea' }, { name: 'Newport' }],
  MH: [{ name: 'Mumbai' }, { name: 'Pune' }, { name: 'Nagpur' }],
  DL: [{ name: 'New Delhi' }],
  KA: [{ name: 'Bengaluru' }, { name: 'Mysuru' }, { name: 'Hubli' }],
  AP: [{ name: 'Visakhapatnam' }, { name: 'Vijayawada' }, { name: 'Guntur' }],
  AR: [{ name: 'Itanagar' }, { name: 'Naharlagun' }],
  AS: [{ name: 'Guwahati' }, { name: 'Dispur' }, { name: 'Dibrugarh' }],
  BR: [{ name: 'Patna' }, { name: 'Gaya' }, { name: 'Bhagalpur' }],
  CG: [{ name: 'Raipur' }, { name: 'Bhilai' }, { name: 'Bilaspur' }],
  GA: [{ name: 'Panaji' }, { name: 'Vasco da Gama' }, { name: 'Margao' }],
  GJ: [{ name: 'Ahmedabad' }, { name: 'Surat' }, { name: 'Vadodara' }],
  HR: [{ name: 'Faridabad' }, { name: 'Gurugram' }, { name: 'Panipat' }],
  HP: [{ name: 'Shimla' }, { name: 'Dharamshala' }, { name: 'Solan' }],
  JH: [{ name: 'Ranchi' }, { name: 'Jamshedpur' }, { name: 'Dhanbad' }],
  KL: [{ name: 'Thiruvananthapuram' }, { name: 'Kochi' }, { name: 'Kozhikode' }],
  MP: [{ name: 'Indore' }, { name: 'Bhopal' }, { name: 'Jabalpur' }],
  MN: [{ name: 'Imphal' }],
  ML: [{ name: 'Shillong' }],
  MZ: [{ name: 'Aizawl' }],
  NL: [{ name: 'Kohima' }, { name: 'Dimapur' }],
  OR: [{ name: 'Bhubaneswar' }, { name: 'Cuttack' }, { name: 'Rourkela' }],
  PB: [{ name: 'Ludhiana' }, { name: 'Amritsar' }, { name: 'Jalandhar' }],
  RJ: [{ name: 'Jaipur' }, { name: 'Jodhpur' }, { name: 'Udaipur' }],
  SK: [{ name: 'Gangtok' }],
  TN: [{ name: 'Chennai' }, { name: 'Coimbatore' }, { name: 'Madurai' }],
  TG: [{ name: 'Hyderabad' }, { name: 'Warangal' }, { name: 'Nizamabad' }],
  TR: [{ name: 'Agartala' }],
  UP: [{ name: 'Lucknow' }, { name: 'Kanpur' }, { name: 'Agra' }],
  UT: [{ name: 'Dehradun' }, { name: 'Haridwar' }, { name: 'Roorkee' }],
  WB: [{ name: 'Kolkata' }, { name: 'Howrah' }, { name: 'Durgapur' }],
  AN: [{ name: 'Port Blair' }],
  CH: [{ name: 'Chandigarh' }],
  DH: [{ name: 'Daman' }, { name: 'Diu' }, { name: 'Silvassa' }],
  JK: [{ name: 'Srinagar' }, { name: 'Jammu' }],
  LA: [{ name: 'Leh' }, { name: 'Kargil' }],
  LD: [{ name: 'Kavaratti' }],
  PY: [{ name: 'Puducherry' }],
};
